"""Build SimulationCraft input: baseline from snapshot + profilesets for candidates.

Baseline uses `local_json` (Blizzard Armory JSON saved from our snapshot) —
recommended over `armory=` in profilesets (wiki: slows init).
"""
import json
from dataclasses import dataclass, field

SLOT_MAP = {
    "HEAD": "head", "SHOULDER": "shoulder", "CHEST": "chest", "BACK": "back",
    "WRIST": "wrist", "HANDS": "hands", "WAIST": "waist", "LEGS": "legs",
    "FEET": "feet", "NECK": "neck", "FINGER_1": "finger1", "FINGER_2": "finger2",
    "TRINKET_1": "trinket1", "TRINKET_2": "trinket2", "MAIN_HAND": "main_hand",
    "OFF_HAND": "off_hand", "TABARD": "tabard", "SHIRT": "shirt",
}


@dataclass
class Candidate:
    item_id: int
    name: str
    slot: str  # canonical simc slot, e.g. trinket1
    item_level: int
    bonus_ids: list[int] = field(default_factory=list)
    gems: list[str] = field(default_factory=list)  # simc gem strings
    enchant_id: int | None = None
    replace_slot: str | None = None  # for trinkets: which worn trinket is replaced
    source: str = ""     # "raid" / "mplus"
    boss_or_dungeon: str = ""
    upgrade_track: str | None = None
    tier: bool = False


def _item_line(candidate: Candidate) -> str:
    parts = [f"id={candidate.item_id}"]
    if candidate.bonus_ids:
        parts.append("bonus_id=" + "/".join(str(b) for b in candidate.bonus_ids))
    if candidate.enchant_id:
        parts.append(f"enchant_id={candidate.enchant_id}")
    for g in candidate.gems:
        parts.append(f"gem_id={g}")
    if candidate.item_level:
        parts.append(f"ilevel={candidate.item_level}")
    return ",".join(parts)


def build_baseline(snapshot_raw: dict) -> str:
    """Produce baseline .simc text from stored snapshot.

    Two snapshot shapes:
    - simc_addon_import: raw['parsed']['gear'] = gear .simc lines → paste directly
    - blizzard_armory:   equipment JSON → local_json armory import
    """
    parsed = snapshot_raw.get("parsed") or {}
    gear = parsed.get("gear")
    if gear:
        return str(gear)
    eq = snapshot_raw.get("equipment", {})
    lines = ["# generated by wow-gear-optymizer", ""]
    lines.append("# local armory json (equipment payload from Blizzard API)")
    lines.append('local_json=' + json.dumps(eq, separators=(",", ":")))
    lines.append("")
    return "\n".join(lines)


def build_profileset_input(
    snapshot_raw: dict,
    candidates: list[Candidate],
    profile_type: str,  # "raid" | "mplus"
    sim_config: dict,
) -> str:
    """Full simc input: baseline + profileset per candidate."""
    cfg_raid = profile_type == "raid"
    lines = [build_baseline(snapshot_raw), ""]
    lines += [
        f"threads={sim_config.get('threads', 8)}",
        f"iterations={sim_config['iterations']}",
        f"target_error={sim_config['target_error']}",
        f"fight_style={sim_config['fight_style']}",
        f"duration={sim_config['duration']}",
        "profileset_metric=dps",
        f"profileset_work_threads={sim_config.get('profileset_work_threads', 2)}",
        "",
    ]
    for c in candidates:
        name = f"{c.source}_{c.item_id}_{c.slot}"
        if c.replace_slot and c.replace_slot != c.slot:
            name += f"_replaces_{c.replace_slot}"
        lines.append(f'profileset."{name}"={_item_line(c)}')
        # replacing a trinket: drop the worn one in that slot
        if c.replace_slot and c.replace_slot != c.slot:
            lines.append(f'profileset."{name}"+=# removes worn item in {c.replace_slot}')
            # simc: specifying the slot with a new item replaces it; explicit removal
            # handled by the item line above binding to the replaced slot
            lines[-1] = f'profileset."{name}"={_item_line(c)}'
        lines.append("")
    return "\n".join(lines)


def build_combined_input(
    snapshot_raw: dict,
    raid_candidates: list[Candidate],
    mplus_candidates: list[Candidate],
    sim_config: dict,
) -> str:
    """Two profile types in one run — profilesets namespaced raid_/mplus_."""
    cfg = dict(sim_config)
    lines = [build_baseline(snapshot_raw), ""]
    for ptype, cands, style in (
        ("raid", raid_candidates, sim_config.get("raid_fight_style", "Patchwerk")),
        ("mplus", mplus_candidates, sim_config.get("mplus_fight_style", "DungeonSlice")),
    ):
        lines += [
            f"# --- {ptype} profilesets",
            f"fight_style={style}",
            f"iterations={cfg[f'{ptype}_iterations']}",
            f"target_error={cfg[f'{ptype}_target_error']}",
            f"duration={cfg.get(f'{ptype}_duration', cfg.get('duration', 300))}",
            "",
        ]
        for c in cands:
            name = f"{ptype}_{c.source}_{c.item_id}_{c.slot}"
            lines.append(f'profileset."{name}"={_item_line(c)}')
            lines.append("")
    return "\n".join(lines)
