"""Build SimulationCraft input: baseline from snapshot + profilesets for candidates.

Baseline uses `local_json` (Blizzard Armory JSON saved from our snapshot) —
recommended over `armory=` in profilesets (wiki: slows init).
"""
import json
from dataclasses import dataclass, field

def _equipment_realm(snapshot_raw: dict) -> str:
    realm = (snapshot_raw.get("equipment") or {}).get("character") or {}
    realm = realm.get("realm") or {}
    if isinstance(realm, dict):
        return realm.get("slug") or realm.get("name") or ""
    return str(realm or "")


SLOT_MAP = {
    "HEAD": "head", "SHOULDER": "shoulder", "CHEST": "chest", "BACK": "back",
    "WRIST": "wrist", "HANDS": "hands", "WAIST": "waist", "LEGS": "legs",
    "FEET": "feet", "NECK": "neck", "FINGER_1": "finger1", "FINGER_2": "finger2",
    "TRINKET_1": "trinket1", "TRINKET_2": "trinket2", "MAIN_HAND": "main_hand",
    "OFF_HAND": "off_hand", "TABARD": "tabard", "SHIRT": "shirt",
}


@dataclass
class Candidate:
    item_id: int
    name: str
    slot: str  # canonical simc slot, e.g. trinket1
    item_level: int
    bonus_ids: list[int] = field(default_factory=list)
    gems: list[str] = field(default_factory=list)  # simc gem strings
    enchant_id: int | None = None
    replace_slot: str | None = None  # for trinkets: which worn trinket is replaced
    source: str = ""     # "raid" / "mplus"
    boss_or_dungeon: str = ""
    upgrade_track: str | None = None
    tier: bool = False
    pset: str = ""       # profileset name override (combos)
    off_item_id: int = 0
    off_bonus_ids: list[int] = field(default_factory=list)
    off_ilevel: int = 0


# SimC gear slot names: canonical slot → simc option (shoulders/wrists plural).
# Profileset gear overrides REQUIRE the slot prefix with `=`
# (profileset."x"=head=id=...,bonus_id=...); a bare `id=...` or `head,id=...`
# is silently IGNORED by SimC (verified live: "Unknown option 'head,id'").
SIMC_SLOT = {"shoulder": "shoulders", "wrist": "wrists"}


def _simc_slot(slot: str) -> str:
    return SIMC_SLOT.get(slot, slot)


def _item_spec(item_id: int, bonus_ids: list[int], enchant_id: int | None,
               gems: list[str], item_level: int) -> str:
    parts = [f"id={item_id}"]
    if bonus_ids:
        parts.append("bonus_id=" + "/".join(str(b) for b in bonus_ids))
    if enchant_id:
        parts.append(f"enchant_id={enchant_id}")
    for g in gems:
        parts.append(f"gem_id={g}")
    if item_level:
        parts.append(f"ilevel={item_level}")
    return ",".join(parts)


def _item_line(candidate: Candidate) -> str:
    slot = _simc_slot(candidate.replace_slot or candidate.slot)
    main = _item_spec(candidate.item_id, candidate.bonus_ids,
                      candidate.enchant_id, candidate.gems, candidate.item_level)
    if candidate.off_item_id:
        # 1H + off-hand combo replaces both slots at once (options joined by /)
        off = _item_spec(candidate.off_item_id, candidate.off_bonus_ids,
                         None, [], candidate.off_ilevel)
        return f"main_hand={main}/off_hand={off}"
    return f"{slot}={main}"


def build_baseline(snapshot_raw: dict, fallback_realm: str = "",
                   fallback_name: str = "") -> str:
    """Produce baseline .simc text from stored snapshot.

    Two snapshot shapes:
    - simc_addon_import: raw['parsed'] holds the FULL simc profile text
      (incl. mage="Name", spec=, talents=) → paste directly. Gear slot lines
      MUST come after the player declaration, which the addon export guarantees.
    - blizzard_armory: native `armory=region,realm,name` import (the worker
      appends the API key from env, so the secret never lands in the DB).
      local_json is NOT used: SimC mangles inline JSON into an armory spec
      ("Invalid region") and file-based local_json ignores embedded gear,
      re-downloading by href anyway.
    """
    parsed = snapshot_raw.get("parsed") or {}
    profile_text = parsed.get("profile_text") or parsed.get("gear")
    if profile_text:
        return str(profile_text)
    summary = snapshot_raw.get("summary", {}) or {}
    name = (summary.get("name") or fallback_name or "").lower()
    realm = (((summary.get("realm") or {}).get("slug"))
             or _equipment_realm(snapshot_raw) or fallback_realm or "").lower()
    try:
        from ..config import get_settings
        region = (get_settings().blizzard_region or "eu").lower()
    except Exception:
        region = "eu"
    lines = ["# generated by player", ""]
    lines.append(f"armory={region},{realm},{name}")
    # pin the ACTIVE spec: sim exactly the talents shown on the report
    active_spec = (((snapshot_raw.get("specializations") or {})
                    .get("active_specialization") or {}).get("name") or "")
    if active_spec:
        lines.append(f"spec={active_spec.lower().replace(' ', '_')}")
    lines.append("")
    return "\n".join(lines)


def build_profileset_input(
    snapshot_raw: dict,
    candidates: list[Candidate],
    profile_type: str,  # "raid" | "mplus"
    sim_config: dict,
    fallback_realm: str = "", fallback_name: str = "",
) -> str:
    """Full simc input: baseline + profileset per candidate."""
    cfg_raid = profile_type == "raid"
    # Sim options must come BEFORE the player block; gear lines must come
    # after the player declaration (which the baseline text guarantees).
    lines = [
        f"threads={sim_config.get('threads', 8)}",
        f"iterations={sim_config['iterations']}",
        f"target_error={sim_config['target_error']}",
        f"fight_style={sim_config['fight_style']}",
        f"max_time={sim_config['duration']}",
        "profileset_metric=dps",
        f"profileset_work_threads={sim_config.get('profileset_work_threads', 2)}",
        "",
    ]
    lines.append(build_baseline(snapshot_raw, fallback_realm, fallback_name))
    lines.append("")
    for c in candidates:
        name = c.pset or f"{c.source}_{c.item_id}_{c.slot}"
        if not c.pset and c.replace_slot and c.replace_slot != c.slot:
            name += f"_replaces_{c.replace_slot}"
        lines.append(f'profileset."{name}"={_item_line(c)}')
        lines.append("")
    return "\n".join(lines)


def build_combined_input(
    snapshot_raw: dict,
    raid_candidates: list[Candidate],
    mplus_candidates: list[Candidate],
    sim_config: dict,
) -> str:
    """Two profile types in one run — profilesets namespaced raid_/mplus_."""
    cfg = dict(sim_config)
    lines = [build_baseline(snapshot_raw), ""]
    for ptype, cands, style in (
        ("raid", raid_candidates, sim_config.get("raid_fight_style", "Patchwerk")),
        ("mplus", mplus_candidates, sim_config.get("mplus_fight_style", "DungeonSlice")),
    ):
        lines += [
            f"# --- {ptype} profilesets",
            f"fight_style={style}",
            f"iterations={cfg[f'{ptype}_iterations']}",
            f"target_error={cfg[f'{ptype}_target_error']}",
            f"duration={cfg.get(f'{ptype}_duration', cfg.get('duration', 300))}",
            "",
        ]
        for c in cands:
            name = f"{ptype}_{c.source}_{c.item_id}_{c.slot}"
            lines.append(f'profileset."{name}"={_item_line(c)}')
            lines.append("")
    return "\n".join(lines)
